config/routes.rb
Rails.application.routes.draw do
  scope 'prices', as: 'prices' do
    get ':vehicle', to: 'prices#index'
    get ':vehicle/edit', to: 'prices#edit', as: 'edit'
    post ':vehicle', to: 'prices#update'
  end

  resources :days

  get 'vehicles', to: 'vehicles#fetch', defaults: {format: 'json'}
  resources :vehicles

  devise_for :users

  root 'dashboard#index'

  scope 'dashboard', as: 'dashboard' do
    post 'calculate', to: 'dashboard#calculate_prices', as: 'calculate'
    get 'dates', to: 'dashboard#load_dates', as: 'dates'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/day.rb
class Day < ApplicationRecord
  CATEGORY_SUMMER = 'S'
  CATEGORY_VALLEY = 'V'
  CATEGORY_PEAK = 'P'
  CATEGORY_HOLIDAY = 'H'

  def self.categories
    {
        self::CATEGORY_SUMMER => 'Summer',
        self::CATEGORY_VALLEY => 'Valley',
        self::CATEGORY_PEAK => 'Peak',
        self::CATEGORY_HOLIDAY => 'Holiday',
    }
  end

  has_many :days_vehicles

  def data
    self[:data].strftime I18n.t('date_format')
  end

  def data=(date)
    self[:data] = Date.strptime date, I18n.t('date_format')
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  def index
    @days = Day.all.order(data: :desc, id: :desc)
  end

  def show

  end

  def new
    @day = Day.new
    @vehicles = Vehicle.all
  end

  def create
    start_date = Date.strptime params[:day][:start_date], t('date_format')
    end_date = Date.strptime params[:day][:end_date], t('date_format')

    (start_date..end_date).each do |date|
      day = Day.new

      day.data = date.strftime t('date_format')
      day.categoria = params[:day][:categoria]

      if day.save
        params[:day][:vehicles].each do |v|
          day_vehicle = DaysVehicle.new

          day_vehicle.vehicle_id = v
          day_vehicle.day_id = day.id

          day_vehicle.save
        end
      end
    end

    redirect_to days_path, notice: t('save_success')
  end

  def edit
    @vehicles = Vehicle.all
  end

  def update
    if @day.update(day_params)
      DaysVehicle.where(day_id: @day.id).destroy_all

      params[:day][:vehicles].each do |v|
        day_vehicle = DaysVehicle.new

        day_vehicle.vehicle_id = v
        day_vehicle.day_id = @day.id

        day_vehicle.save
      end

      redirect_to days_path, notice: t('save_success')
    end
  end

  def destroy
    @day.destroy
    respond_to do |format|
      format.html {redirect_to days_path, notice: t('delete_success')}
      format.json {head :no_content}
    end
  end

  def self.get_day_category date, vehicle
    day = DaysVehicle.joins(:day).where(days: {data: date}, vehicle_id: vehicle.id).last

    if day
      day.day.categoria
    else
      if date.strftime('%A') == I18n.t('saturday') or date.strftime('%A') == I18n.t('sunday') or date.strftime('%A') == I18n.t('friday')
        return Day::CATEGORY_PEAK
      else
        return Day::CATEGORY_VALLEY
      end
    end
  end

  private

  def day_params
    params.require(:day).permit(:data, :categoria)
  end

  def set_day
    @day = Day.find(params[:id])
  end
end

app/helpers/days_helper.rb
module DaysHelper
  def get_class_flags day
    if day.strftime('%A') == t('saturday') or day.strftime('%A') == t('sunday')
      'text-danger'
    end
  end

  def get_class_flags_with_categories day, category
    if day.strftime('%A') == t('saturday') or day.strftime('%A') == t('sunday')
      return 'text-danger'
    end

    if category == Day::CATEGORY_HOLIDAY
      'text-danger'
    end
  end

  def get_vehicles_in_date day
    day.days_vehicles.map do |dv|
      dv.vehicle.nome
    end
  end

  def get_checked_vehicles day, vehicle_id
    checked = false

    if params[:id]
      day.days_vehicles.each do |dv|
        if dv.vehicle_id == vehicle_id
          return checked = true
        end
      end
    end
  end
end

app/views/days/_form.html.erb
<%= form_with(model: day, local: true, id: 'days-form') do |form| %>
    <div class="box">
      <div class="box-body">
        <% if params[:id].nil? %>
            <label><%= Day.human_attribute_name('period') %></label>

            <label id="period-error-label" class="side-error"></label>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <div class="input-group input-daterange">
                    <%= form.text_field 'start_date', class: 'form-control', id: 'day-start-date' %>

                    <div class="input-group-addon"><%= t('to') %></div>

                    <%= form.text_field 'end_date', class: 'form-control', id: 'day-end-date' %>
                  </div>
                </div>
              </div>
            </div>
        <% else %>
            <label><%= Day.human_attribute_name('data') %></label>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= form.text_field 'data', class: 'form-control', id: 'day-date' %>
                </div>
              </div>
            </div>
        <% end %>

        <label><%= Day.human_attribute_name('categoria') %></label>

        <label id="category-error-label" class="side-error"></label>

        <% Day.categories.each do |key, c| %>
            <div class="radio">
              <label>
                <%= form.radio_button 'categoria', key %>
                <%= c %>
              </label>
            </div>
        <% end %>

        <label><%= Day.human_attribute_name('vehicles') %></label>

        <label id="vehicles-error-label" class="side-error"></label>

        <div class="checkbox">
          <label>
            <input type="checkbox" id="select-all-vehicles-checkbox"/> <%= t('all') %>
          </label>
        </div>

        <% @vehicles.each do |v| %>
            <div class="checkbox">
              <label>
                <%= form.check_box 'vehicles', {multiple: true, class: 'vehicle-checkbox', include_hidden: false, checked: get_checked_vehicles(@day, v.id)}, v.id %>
                <%= v.nome %>
              </label>
            </div>
        <% end %>
      </div>
    </div>

    <%= form.button "<i class='fa fa-check'></i> #{t('save')}".html_safe, class: 'btn btn-success' %>
<% end %>

app/views/days/edit.html.erb
<section class="content-header">
  <h1><%= Day.model_name.human(count: 2) %></h1>
</section>

<section class="content">
  <%= render 'form', day: @day %>
</section>

app/views/days/index.html.erb
<section class="content-header">
  <h1><%= Day.model_name.human(count: 2) %></h1>
</section>

<section class="content">
  <nav class="actions-bar">
    <%= link_to "<i class='fa fa-plus'></i> #{t('new')}".html_safe, new_day_path, class: 'btn btn-app' %>
  </nav>

  <div class="box">
    <div class="box-body">
      <table class="table table-hover" id="days-list">
        <thead>
        <tr>
          <th><%= Day.human_attribute_name('data') %></th>
          <th><%= Day.human_attribute_name('categoria') %></th>
          <th><%= Day.human_attribute_name('vehicles') %></th>
          <th><%= t('actions') %></th>
        </tr>
        </thead>
        <tbody>
        <% @days.each do |d| %>
            <tr>
              <td><%= d.data %></td>
              <td><%= d.categoria %></td>
              <td><%= get_vehicles_in_date(d).join(', ') %></td>
              <td>
                <div class="actions-list">
                  <%= link_to t('edit'), edit_day_path(d) %>
                  <%= link_to t('delete'), d, method: :delete, data: {confirm: t('confirm')} %>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/days/new.html.erb
<section class="content-header">
  <h1><%= Day.model_name.human(count: 2) %></h1>
</section>

<section class="content">
  <%= render 'form', day: @day %>
</section>