config/routes.rb
Rails.application.routes.draw do
  scope 'prices', as: 'prices' do
    get ':vehicle', to: 'prices#index'
    get ':vehicle/edit', to: 'prices#edit', as: 'edit'
    post ':vehicle', to: 'prices#update'
  end

  resources :days

  get 'vehicles', to: 'vehicles#fetch', defaults: {format: 'json'}
  resources :vehicles

  devise_for :users

  root 'dashboard#index'

  scope 'dashboard', as: 'dashboard' do
    post 'calculate', to: 'dashboard#calculate_prices', as: 'calculate'
    get 'dates', to: 'dashboard#load_dates', as: 'dates'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/price.rb
class Price < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  belongs_to :vehicle

  MIN_HOURS = 3
  MAX_HOURS = 10

  def formatted_valor
    number_to_currency self[:valor], precision: 2, unit: I18n.t('currency.symbol'), separator: I18n.t('currency.decimal'), delimiter: I18n.t('currency.thousands')
  end

  def valor=(valor)
    self[:valor] = valor.gsub(I18n.t('currency.thousands'), '').gsub(I18n.t('currency.symbol'), '')
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_vehicle, only: [:index, :edit, :update]

  # GET /prices
  # GET /prices.json
  def index
    query = Price.where(vehicle_id: @vehicle.id)

    @prices = {}
    query.each do |p|
      @prices[p.horas] ||= {}
      @prices[p.horas][p.categoria] = p.valor
    end
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
    query = Price.where(vehicle_id: @vehicle.id)

    @prices = {}
    query.each do |p|
      @prices[p.horas] ||= {}
      @prices[p.horas][p.categoria] = p.valor
    end
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html {redirect_to @price, notice: 'Price was successfully created.'}
        format.json {render :show, status: :created, location: @price}
      else
        format.html {render :new}
        format.json {render json: @price.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    params[:values].each do |hour, v|
      v.each do |category, v2|
        price = Price.where(vehicle_id: @vehicle.id, horas: hour, categoria: category).first_or_create

        price.valor = v2
        price.categoria = category
        price.horas = hour
        price.vehicle_id = @vehicle.id

        price.save
      end
    end

    respond_to do |format|
      format.html {redirect_to prices_path(@vehicle), notice: t('save_success')}
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html {redirect_to prices_url, notice: 'Price was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def self.calculate_prices start_date, end_date, vehicle, hours
    start_date = Date.strptime start_date, I18n.t('date_format')
    end_date = Date.strptime end_date, I18n.t('date_format')

    (start_date..end_date).map do |date|
      category = DaysController.get_day_category date, vehicle
      price = Price.where(vehicle_id: vehicle.id, categoria: category, horas: hours).first

      {date: date, category: category, price: (price) ? price.valor : 0}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_price
    @price = Price.find(params[:id])
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_params
    params.require(:price).permit(:valor, :categoria, :horas, :vehicle_id)
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: price, local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :price_valor %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria, id: :price_categoria %>
  </div>

  <div class="field">
    <%= form.label :horas %>
    <%= form.number_field :horas, id: :price_horas %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.text_field :vehicle_id, id: :price_vehicle_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<section class="content-header">
  <h1><%= Price.model_name.human(count: 2) %>
    <small><%= @vehicle.nome %></small>
  </h1>
</section>

<section class="content">
  <%= form_with url: prices_path(@vehicle), local: true do |f| %>

      <div class="box">
        <div class="box-body">
          <table class="table table-hover">
            <thead>
            <tr>
              <th></th>

              <% Day.categories.each do |key, c| %>
                  <th><%= c %></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <% (Price::MIN_HOURS..Price::MAX_HOURS).each do |h| %>
                <tr>
                  <th><%= t('activerecord.attributes.price.horas', count: h) %></th>

                  <% Day.categories.each do |key, c| %>
                      <%
                        if @prices[h]
                          if @prices[h][key]
                            value = @prices[h][key]
                          end
                        end
                      %>

                      <td><%= text_field_tag "values[#{h}][#{key}]", value, class: 'form-control mask-money' %></td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <%= f.button "<i class='fa fa-check'></i> #{t('save')}".html_safe, class: 'btn btn-success' %>
  <% end %>
</section>

app/views/prices/index.html.erb
<section class="content-header">
  <h1><%= Price.model_name.human(count: 2) %>
    <small><%= @vehicle.nome %></small>
  </h1>
</section>

<section class="content">
  <nav class="actions-bar">
    <%= link_to "<i class='fa fa-pencil'></i> #{t('edit')}".html_safe, prices_edit_path(@vehicle), class: 'btn btn-app' %>
  </nav>

  <div class="box">
    <div class="box-body">
      <table class="table table-hover">
        <thead>
        <tr>
          <th></th>

          <% Day.categories.each do |key, c| %>
              <th><%= c %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% (Price::MIN_HOURS..Price::MAX_HOURS).each do |h| %>
            <tr>
              <th><%= t('activerecord.attributes.price.horas', count: h) %></th>

              <% Day.categories.each do |key, c| %>
                  <td>
                    <%
                      if @prices[h]
                        if @prices[h][key]
                          concat @prices[h][key]
                        end
                      end
                    %>
                  </td>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor:</strong>
  <%= @price.valor %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @price.categoria %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @price.horas %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @price.vehicle %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>