config/routes.rb
Rails.application.routes.draw do
  scope 'prices', as: 'prices' do
    get ':vehicle', to: 'prices#index'
    get ':vehicle/edit', to: 'prices#edit', as: 'edit'
    post ':vehicle', to: 'prices#update'
  end

  resources :days

  get 'vehicles', to: 'vehicles#fetch', defaults: {format: 'json'}
  resources :vehicles

  devise_for :users

  root 'dashboard#index'

  scope 'dashboard', as: 'dashboard' do
    post 'calculate', to: 'dashboard#calculate_prices', as: 'calculate'
    get 'dates', to: 'dashboard#load_dates', as: 'dates'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :nome, presence: true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:fetch]
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
    @vehicle = Vehicle.new
  end

  def fetch
    @vehicles = Vehicle.all

    render json: @vehicles
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html {redirect_to vehicles_path, notice: t('save_success')}
        format.json {render :show, status: :created, location: @vehicle}
      else
        format.html {render :new}
        format.json {render json: @vehicle.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html {redirect_to vehicles_path, notice: t('save_success')}
        format.json {render :show, status: :ok, location: @vehicle}
      else
        format.html {render :edit}
        format.json {render json: @vehicle.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html {redirect_to vehicles_url, notice: t('delete_success')}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vehicle_params
    params.require(:vehicle).permit(:nome)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
    <% if vehicle.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

          <ul>
            <% vehicle.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="box">
      <div class="box-body">
        <div class="form-group">
          <%= form.label :nome %>
          <%= form.text_field :nome, class: 'form-control' %>
        </div>
      </div>
    </div>

    <%= form.button "<i class='fa fa-check'></i> #{t('save')}".html_safe, class: 'btn btn-success' %>
<% end %>

app/views/vehicles/edit.html.erb
<section class="content-header">
  <h1><%= Vehicle.model_name.human(count: 2) %></h1>
</section>

<section class="content">
  <%= render 'form', vehicle: @vehicle %>
</section>

app/views/vehicles/index.html.erb
<section class="content-header">
  <h1><%= Vehicle.model_name.human(count: 2) %></h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6">
      <%= render 'form', vehicle: @vehicle %>
    </div>

    <div class="col-md-6">
      <div class="box">
        <div class="box-body">
          <table id="vehicles-list" class="table table-hover">
            <thead>
            <tr>
              <th><%= Vehicle.human_attribute_name('nome') %></th>
              <th><%= t('actions') %></th>
            </tr>
            </thead>
            <tbody>
            <% @vehicles.each do |vehicle| %>
                <tr>
                  <td><%= vehicle.nome %></td>
                  <td>
                    <div class="actions-list">
                      <%= link_to t('edit'), edit_vehicle_path(vehicle) %>
                      <%= link_to Price.model_name.human(count: 2), prices_path(vehicle) %>
                      <%= link_to t('delete'), vehicle, method: :delete, data: {confirm: t('confirm')} %>
                    </div>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/vehicles/new.html.erb
<section class="content-header">
  <h1><%= Vehicle.model_name.human(count: 2) %></h1>
</section>

<section class="content">
  <%= render 'form', vehicle: @vehicle %>
</section>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>